application_name: MyApp
application_version: 1.0.0
client_id: '587531323739-snvpup1g3r6uhb5vu5qrm9gc5sidtftl.apps.googleusercontent.com'
client_secret: 'ASSTmw52PGKc5D3CAGw0hGwW'
access_token: 'ya29.gAIoHNz9yY-1PmEC3rrtLfm6JUAcDDBqb6bhLupERKg9aJrSDDhX3Z35q7i4R48MIlnP'
refresh_token: ''