application_name: MyApp
application_version: 1.0.0
client_id: '587531323739-ergcv4bhhkhgose887l9ssipssjoc4cu.apps.googleusercontent.com'
client_secret: 'Bpktmd0J_QNtTrcd1TOJFGTS'
access_token: 'ya29.gAKREcr8KK2ADhXaMRvlwi7TNRlmTTXvbWmc3Ug8q7hXIALT2JzPEz_pL7MSGyJFoxio'
refresh_token: '1/XLv37Id3jI5t28qogmjVOcqgo_BOwZmSha7hR9gAkO8'